version: "3"
services:
    node-rest:
        container_name: node-rest
        build: 
            context: ./node-rest
            dockerfile: Dockerfile
        volumes:
            - ./node-rest:/app
            - /app/node_modules
        environment:
            PORT: 3000
        ports:
            - 3000:3000
        command: npm run start

    node-bot:
        container_name: node-bot
        build:
            context: ./node-bot
            dockerfile: Dockerfile
        volumes:
            - ./node-bot:/app
            - /app/node_modules
        depends_on:
            - redis
        environment:
            BOT_NAME: benny
            REDIS_HOST: redis
            REDIS_PORT: 6379
            CLICKS_API_PORT: 3000
        command: npm run start

    redis:
        image: redis
        container_name: redis
        expose:
            - 6379
        ports:
            - 6379:6379