version: "3"
services:
    node-bot:
        container_name: node-bot
        build:
            context: ./node-bot
            dockerfile: Dockerfile
        volumes:
            - ./node_main:/app
            - /app/node_modules
        environment:
            - BOT_NAME: benny
        command: npm run start